Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  StyleGuide: '#english-comments'
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Metrics/LineLength:
  Max: 120
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Max: 3
  CountKeywordArgs: true
Layout/LeadingCommentSpace:
  Enabled: false
Layout/SpaceBeforeComment:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/CaseIndentation:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Layout/AlignParameters:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Lint/Syntax:
  Enabled: false